import type { OnigiriCatalogItem } from './types';

export const INGREDIENTS_PER_ONIGIRI = 4;
export const ONIGIRI_CATALOG_SIZE = 24;

export const TEMP_ONIGIRI_CATALOG = [
  {
    id: 'onigiri-001',
    order: 1,
    name: 'TUNA MAYO',
    ingredients: ['RICE', 'SEAWEED', 'TUNA', 'MAYO'],
    description: 'Classic convenience store favorite.',
    imageKey: 'onigiri-001',
    temporary: true,
  },
  {
    id: 'onigiri-002',
    order: 2,
    name: 'SALMON',
    ingredients: ['RICE', 'SEAWEED', 'SALMON', 'SESAME'],
    description: 'Simple grilled salmon with a clean finish.',
    imageKey: 'onigiri-002',
    temporary: true,
  },
  {
    id: 'onigiri-003',
    order: 3,
    name: 'UMEBOSHI',
    ingredients: ['RICE', 'SEAWEED', 'UME', 'SHISO'],
    description: 'Bright, salty plum for a sharp little wake-up.',
    imageKey: 'onigiri-003',
    temporary: true,
  },
  {
    id: 'onigiri-004',
    order: 4,
    name: 'KONBU',
    ingredients: ['RICE', 'SEAWEED', 'KONBU', 'SOY'],
    description: 'Soft simmered kelp with a quiet savory depth.',
    imageKey: 'onigiri-004',
    temporary: true,
  },
  {
    id: 'onigiri-005',
    order: 5,
    name: 'MENTAIKO',
    ingredients: ['RICE', 'SEAWEED', 'MENTAIKO', 'LEMON'],
    description: 'A small kick of roe and citrus.',
    imageKey: 'onigiri-005',
    temporary: true,
  },
  {
    id: 'onigiri-006',
    order: 6,
    name: 'OKAKA',
    ingredients: ['RICE', 'SEAWEED', 'BONITO', 'SOY'],
    description: 'Bonito flakes folded into warm rice.',
    imageKey: 'onigiri-006',
    temporary: true,
  },
  {
    id: 'onigiri-007',
    order: 7,
    name: 'TAKANA',
    ingredients: ['RICE', 'SEAWEED', 'TAKANA', 'SESAME'],
    description: 'Pickled greens with a crisp, peppery edge.',
    imageKey: 'onigiri-007',
    temporary: true,
  },
  {
    id: 'onigiri-008',
    order: 8,
    name: 'YAKI ONIGIRI',
    ingredients: ['RICE', 'SOY', 'MISO', 'CHAR'],
    description: 'Grilled rice brushed until lightly smoky.',
    imageKey: 'onigiri-008',
    temporary: true,
  },
  {
    id: 'onigiri-009',
    order: 9,
    name: 'EGG MAYO',
    ingredients: ['RICE', 'SEAWEED', 'EGG', 'MAYO'],
    description: 'Soft egg and mayo for a gentle midday stop.',
    imageKey: 'onigiri-009',
    temporary: true,
  },
  {
    id: 'onigiri-010',
    order: 10,
    name: 'CHICKEN SOBORO',
    ingredients: ['RICE', 'SEAWEED', 'CHICKEN', 'GINGER'],
    description: 'Sweet-salty chicken crumble with ginger.',
    imageKey: 'onigiri-010',
    temporary: true,
  },
  {
    id: 'onigiri-011',
    order: 11,
    name: 'KARAAGE',
    ingredients: ['RICE', 'SEAWEED', 'KARAAGE', 'LEMON'],
    description: 'A lunchbox-style bite tucked into rice.',
    imageKey: 'onigiri-011',
    temporary: true,
  },
  {
    id: 'onigiri-012',
    order: 12,
    name: 'KIMCHI',
    ingredients: ['RICE', 'SEAWEED', 'KIMCHI', 'SESAME'],
    description: 'Crunchy, spicy filling with a toasted finish.',
    imageKey: 'onigiri-012',
    temporary: true,
  },
  {
    id: 'onigiri-013',
    order: 13,
    name: 'NATTO',
    ingredients: ['RICE', 'SEAWEED', 'NATTO', 'MUSTARD'],
    description: 'Sticky fermented beans for the brave regular.',
    imageKey: 'onigiri-013',
    temporary: true,
  },
  {
    id: 'onigiri-014',
    order: 14,
    name: 'TENMUSU',
    ingredients: ['RICE', 'SEAWEED', 'SHRIMP', 'TEMPURA'],
    description: 'Tiny tempura shrimp wrapped for the road.',
    imageKey: 'onigiri-014',
    temporary: true,
  },
  {
    id: 'onigiri-015',
    order: 15,
    name: 'EBI MAYO',
    ingredients: ['RICE', 'SEAWEED', 'SHRIMP', 'MAYO'],
    description: 'Creamy shrimp with a convenience-store grin.',
    imageKey: 'onigiri-015',
    temporary: true,
  },
  {
    id: 'onigiri-016',
    order: 16,
    name: 'BEEF SHIGURE',
    ingredients: ['RICE', 'SEAWEED', 'BEEF', 'GINGER'],
    description: 'Slow-simmered beef with a sweet ginger glaze.',
    imageKey: 'onigiri-016',
    temporary: true,
  },
  {
    id: 'onigiri-017',
    order: 17,
    name: 'IKURA',
    ingredients: ['RICE', 'SEAWEED', 'IKURA', 'SHISO'],
    description: 'Bright roe and shiso for a little celebration.',
    imageKey: 'onigiri-017',
    temporary: true,
  },
  {
    id: 'onigiri-018',
    order: 18,
    name: 'SHIO MUSUBI',
    ingredients: ['RICE', 'SALT', 'SEAWEED', 'SESAME'],
    description: 'Plain salted rice, honest and exact.',
    imageKey: 'onigiri-018',
    temporary: true,
  },
  {
    id: 'onigiri-019',
    order: 19,
    name: 'HIJIKI',
    ingredients: ['RICE', 'SEAWEED', 'HIJIKI', 'CARROT'],
    description: 'Sea vegetable and carrot mixed into rice.',
    imageKey: 'onigiri-019',
    temporary: true,
  },
  {
    id: 'onigiri-020',
    order: 20,
    name: 'CORN BUTTER',
    ingredients: ['RICE', 'SEAWEED', 'CORN', 'BUTTER'],
    description: 'Sweet corn with a mellow butter note.',
    imageKey: 'onigiri-020',
    temporary: true,
  },
  {
    id: 'onigiri-021',
    order: 21,
    name: 'AVOCADO',
    ingredients: ['RICE', 'SEAWEED', 'AVOCADO', 'WASABI'],
    description: 'Creamy avocado with a small wasabi spark.',
    imageKey: 'onigiri-021',
    temporary: true,
  },
  {
    id: 'onigiri-022',
    order: 22,
    name: 'MUSHROOM',
    ingredients: ['RICE', 'SEAWEED', 'MUSHROOM', 'SOY'],
    description: 'Earthy mushrooms simmered until glossy.',
    imageKey: 'onigiri-022',
    temporary: true,
  },
  {
    id: 'onigiri-023',
    order: 23,
    name: 'CURRY',
    ingredients: ['RICE', 'SEAWEED', 'CURRY', 'POTATO'],
    description: 'A warm curry pocket for late-night study.',
    imageKey: 'onigiri-023',
    temporary: true,
  },
  {
    id: 'onigiri-024',
    order: 24,
    name: 'SHOP SPECIAL',
    ingredients: ['RICE', 'SEAWEED', 'CHOICE', 'THANKS'],
    description: 'The final placeholder until the real special arrives.',
    imageKey: 'onigiri-024',
    temporary: true,
  },
] as const satisfies readonly OnigiriCatalogItem[];

export type OnigiriCatalogId = (typeof TEMP_ONIGIRI_CATALOG)[number]['id'];

export function getOnigiriById(id: string): OnigiriCatalogItem | null {
  return TEMP_ONIGIRI_CATALOG.find((item) => item.id === id) ?? null;
}

export function getOnigiriByOrder(order: number): OnigiriCatalogItem | null {
  return TEMP_ONIGIRI_CATALOG.find((item) => item.order === order) ?? null;
}
