import type { OnigiriCatalogItem } from './types';

export const INGREDIENTS_PER_ONIGIRI = 4;
export const ONIGIRI_CATALOG_SIZE = 24;

// 이름·재료는 한국어 표시용 (핸드오프: 영문 라벨을 한국어로, ONIGIRI 워드마크만 남긴다).
// id·order·imageKey 는 진행도가 매달려 있으므로 바꾸지 않는다.
// 재료 키는 ingredientAssets 의 아트가 있는 것만 쓴다.
export const TEMP_ONIGIRI_CATALOG = [
  {
    id: 'onigiri-001',
    order: 1,
    name: '참치마요',
    ingredients: ['RICE', 'NORI', 'TUNA', 'MAYO'],
    description: '편의점 진열대의 그 맛. 시작은 늘 이거였다.',
    imageKey: 'onigiri-001',
    temporary: true,
  },
  {
    id: 'onigiri-002',
    order: 2,
    name: '연어',
    ingredients: ['RICE', 'NORI', 'SALMON', 'SALT'],
    description: '구운 연어 한 조각, 소금으로 마무리.',
    imageKey: 'onigiri-002',
    temporary: true,
  },
  {
    id: 'onigiri-003',
    order: 3,
    name: '우메보시',
    ingredients: ['RICE', 'NORI', 'UMEBOSHI', 'SESAME'],
    description: '시고 짜다. 잠이 확 깬다.',
    imageKey: 'onigiri-003',
    temporary: true,
  },
  {
    id: 'onigiri-004',
    order: 4,
    name: '깻잎',
    ingredients: ['RICE', 'NORI', 'PERILLA', 'SESAME_OIL'],
    description: '깻잎 한 장에 참기름 조금.',
    imageKey: 'onigiri-004',
    temporary: true,
  },
  {
    id: 'onigiri-005',
    order: 5,
    name: '매콤참치',
    ingredients: ['RICE', 'NORI', 'TUNA', 'GOCHUJANG'],
    description: '참치마요에 고추장을 얹으면 다른 물건이 된다.',
    imageKey: 'onigiri-005',
    temporary: true,
  },
  {
    id: 'onigiri-006',
    order: 6,
    name: '명란',
    ingredients: ['RICE', 'NORI', 'POLLOCK_ROE', 'BUTTER'],
    description: '명란에 버터. 반칙이지만 맛있다.',
    imageKey: 'onigiri-006',
    temporary: true,
  },
  {
    id: 'onigiri-007',
    order: 7,
    name: '연어알',
    ingredients: ['RICE', 'NORI', 'SALMON_ROE', 'GREEN_ONION'],
    description: '톡 터지는 알과 쪽파.',
    imageKey: 'onigiri-007',
    temporary: true,
  },
  {
    id: 'onigiri-008',
    order: 8,
    name: '팥',
    ingredients: ['RICE', 'RED_BEAN', 'SOYBEAN_POWDER', 'SALT'],
    description: '달지 않게. 콩가루로 마무리한다.',
    imageKey: 'onigiri-008',
    temporary: true,
  },
  {
    id: 'onigiri-009',
    order: 9,
    name: '완두콩',
    ingredients: ['RICE', 'GREEN_PEAS', 'SALT', 'BUTTER'],
    description: '봄에 나오는 것만 쓴다.',
    imageKey: 'onigiri-009',
    temporary: true,
  },
  {
    id: 'onigiri-010',
    order: 10,
    name: '새우튀김',
    ingredients: ['RICE', 'NORI', 'SHRIMP_TEMPURA', 'SAUCE'],
    description: '꼬리가 삐져나온 게 정석이다.',
    imageKey: 'onigiri-010',
    temporary: true,
  },
  {
    id: 'onigiri-011',
    order: 11,
    name: '불고기',
    ingredients: ['RICE', 'NORI', 'BULGOGI', 'ONION'],
    description: '양파를 같이 볶아야 물기가 안 돈다.',
    imageKey: 'onigiri-011',
    temporary: true,
  },
  {
    id: 'onigiri-012',
    order: 12,
    name: '김치',
    ingredients: ['RICE', 'NORI', 'KIMCHI', 'SESAME_OIL'],
    description: '잘 익은 걸로. 물기는 꼭 짠다.',
    imageKey: 'onigiri-012',
    temporary: true,
  },
  {
    id: 'onigiri-013',
    order: 13,
    name: '베이컨치즈',
    ingredients: ['RICE', 'BACON', 'CHEESE', 'PEPPER'],
    description: '후추를 아끼면 밋밋해진다.',
    imageKey: 'onigiri-013',
    temporary: true,
  },
  {
    id: 'onigiri-014',
    order: 14,
    name: '카레',
    ingredients: ['RICE', 'CURRY', 'POTATO', 'CARROT'],
    description: '전날 남은 카레가 제일 낫다.',
    imageKey: 'onigiri-014',
    temporary: true,
  },
  {
    id: 'onigiri-015',
    order: 15,
    name: '계란마요',
    ingredients: ['RICE', 'NORI', 'EGG', 'MAYO'],
    description: '삶은 계란을 대충 으깬다.',
    imageKey: 'onigiri-015',
    temporary: true,
  },
  {
    id: 'onigiri-016',
    order: 16,
    name: '된장',
    ingredients: ['RICE', 'DOENJANG', 'GREEN_ONION', 'SESAME'],
    description: '구워서 겉을 살짝 태운다.',
    imageKey: 'onigiri-016',
    temporary: true,
  },
  {
    id: 'onigiri-017',
    order: 17,
    name: '우엉',
    ingredients: ['RICE', 'NORI', 'BURDOCK', 'SAUCE'],
    description: '가늘게 채 썰어 조린 우엉.',
    imageKey: 'onigiri-017',
    temporary: true,
  },
  {
    id: 'onigiri-018',
    order: 18,
    name: '후리카케',
    ingredients: ['RICE', 'FURIKAKE', 'SESAME', 'SALT'],
    description: '아무것도 없는 날의 답.',
    imageKey: 'onigiri-018',
    temporary: true,
  },
  {
    id: 'onigiri-019',
    order: 19,
    name: '새우마요',
    ingredients: ['RICE', 'NORI', 'SHRIMP', 'MAYO'],
    description: '새우는 굵은 걸 쓴다.',
    imageKey: 'onigiri-019',
    temporary: true,
  },
  {
    id: 'onigiri-020',
    order: 20,
    name: '데리야키',
    ingredients: ['RICE', 'NORI', 'TERIYAKI', 'SESAME'],
    description: '달고 짠 소스가 밥에 배게 둔다.',
    imageKey: 'onigiri-020',
    temporary: true,
  },
  {
    id: 'onigiri-021',
    order: 21,
    name: '감자버터',
    ingredients: ['RICE', 'POTATO', 'BUTTER', 'PARSLEY'],
    description: '뜨거울 때 버터를 올려야 녹는다.',
    imageKey: 'onigiri-021',
    temporary: true,
  },
  {
    id: 'onigiri-022',
    order: 22,
    name: '고추마요',
    ingredients: ['RICE', 'NORI', 'CHILI', 'MAYO'],
    description: '매운 걸 좋아하는 손님용.',
    imageKey: 'onigiri-022',
    temporary: true,
  },
  {
    id: 'onigiri-023',
    order: 23,
    name: '흑임자',
    ingredients: ['RICE', 'BLACK_SESAME', 'MILK', 'SALT'],
    description: '고소한 쪽으로 끝까지 간다.',
    imageKey: 'onigiri-023',
    temporary: true,
  },
  {
    id: 'onigiri-024',
    order: 24,
    name: '사장 특선',
    ingredients: ['RICE', 'NORI', 'SALMON', 'WASABI'],
    description: '메뉴판에 없다. 여기까지 온 손님에게만.',
    imageKey: 'onigiri-024',
    temporary: true,
  },
] as const satisfies readonly OnigiriCatalogItem[];

export type OnigiriCatalogId = (typeof TEMP_ONIGIRI_CATALOG)[number]['id'];

export function getOnigiriById(id: string): OnigiriCatalogItem | null {
  return TEMP_ONIGIRI_CATALOG.find((item) => item.id === id) ?? null;
}

export function getOnigiriByOrder(order: number): OnigiriCatalogItem | null {
  return TEMP_ONIGIRI_CATALOG.find((item) => item.order === order) ?? null;
}
